chore: codecov use lcov

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,4 +34,4 @@ jobs:
           FOLDER: public # The folder the action should deploy.
 
       - name: Codecov
-        run: bash <(curl -s https://codecov.io/bash) -f './coverage/clover.xml' -t ${{ secrets.CODECOV_TOKEN }} || echo 'Codecov failed to upload'
+        run: bash <(curl -s https://codecov.io/bash) -f './coverage/lcov.info' -t ${{ secrets.CODECOV_TOKEN }} || echo 'Codecov failed to upload'
